name: Remove Partial Scenes

on:
  - workflow_dispatch
  - push

jobs:
  remove-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Debug media folder
        run: |
          echo "Listing media folder from repo root:"
          ls -R ./media || echo "No media folder found"

      - name: Remove partial movie files
        run: |
          shopt -s globstar nullglob
          echo "Matching files:"
          echo ./media/**/partial_movie_files/**

          rm -rf ./media/**/partial_movie_files/**

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Remove partial movie files"
            git push
            fi
