name: Remove Partial Scenes

on:
  - workflow_dispatch
  - push

jobs:
  remove-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        
      - name: Get PWD
        run: pwd
      - name: get ls
        run: ls -la

      - name: Remove Partial Scene Folders
        run: cd /media/**/partial_movie_files

      - name: ls new dir
        run: ls -la
